In [1]:
import numpy as np

#sample points
p1=[[155,120],[480,120],[20,475],[620,475]]
p2=[[0,0],[400,0],[0,600],[400,600]]
def homography(p1, p2):
  A= []
  for val in range(0,len(p1)):
    x_1 = p1[val][0]
    y_1 = p1[val][1]
    x_2 = p2[val][0] 
    y_2 = p2[val][1]
    A.append([x_1, y_1, 1 ,0 ,0 ,0, -x_2 * x_1, -x_2 * y_1, -x_2 ])
    A.append([0, 0 ,0 ,x_1, y_1, 1, -y_2*x_1, -y_2 * y_1, -y_2 ])

  A=np.array(A)
  u,S,V = np.linalg.svd(A)
  #print(V)
  l= V[-1,:]/V[-1,-1]
  h= np.reshape(l,(3,3))
  return h

#def correct_img():
homography(p1,p2)




array([[ 1.72382398e+00,  6.55538695e-01, -3.45857360e+02],
       [ 9.45400983e-14,  4.37025797e+00, -5.24430956e+02],
       [ 7.41659579e-14,  3.33839150e-03,  1.00000000e+00]])

In [3]:
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

p1=np.array([[155,120],[480,120],[20,475],[620,475]])
p2=np.array([[0,0],[400,0],[0,600],[400,600]])

h, status= cv2.findHomography(p1,p2)
print(h)

[[ 1.72382398e+00  6.55538695e-01 -3.45857360e+02]
 [-5.61587082e-16  4.37025797e+00 -5.24430956e+02]
 [-1.06321633e-18  3.33839150e-03  1.00000000e+00]]
