# Problem 3

The concept of homography in Computer Vision is used to understand, explain and study visual perspective,
and, specifically, the difference in appearance of two plane objects viewed from different points of view. This
concept will be taught in more detail in the coming lectures. For now, you just need to know that given
4 corresponding points on the two different planes, the homography between them is computed using the
following system of equations Ax = 0.

In [1]:
#Import scientific computing package "numpy" 
import numpy as np
from numpy import linalg as la 
np.set_printoptions(suppress=True)

In [2]:
#Insert the A matrix elements here, in this case - the given point correspondences
x1 = 5
x2 = 150
x3 = 150
x4 = 5
y1 = 5
y2 = 5
y3 = 150
y4 = 150
xp1 = 100
xp2 = 200
xp3 = 220
xp4 = 100
yp1 = 100
yp2 = 80
yp3 = 80
yp4 = 200

In [3]:
# Initializing the A matrix 
A = np.array([[-x1, -y1, -1, 0, 0, 0, x1*xp1, y1*xp1, xp1], [0, 0, 0, -x1, -y1, -1, x1*yp1, y1*yp1, yp1], [-x2, -y2, -1, 0, 0, 0, x2*xp2, y2*xp2, xp2], [0, 0, 0, -x2, -y2, -1, x2*yp2, y2*yp2, yp2], [-x3, -y3, -1, 0, 0, 0, x3*xp3, y3*xp3, xp3], [0, 0, 0, -x3, -y3, -1, x3*yp3, y3*yp3, yp3], [-x4, -y4, -1, 0, 0, 0, x4*xp4, y4*xp4, xp4], [0 , 0, 0, -x4, -y4, -1, x4*yp4, y4*yp4, yp4]])

print 'The given A matrix is: '
print A 
print ' '
# Taking transpose of A matrix
At = np.transpose(A)
print 'The Transpose of the A matrix (At) is: '
print At 

The given A matrix is: 
[[   -5    -5    -1     0     0     0   500   500   100]
 [    0     0     0    -5    -5    -1   500   500   100]
 [ -150    -5    -1     0     0     0 30000  1000   200]
 [    0     0     0  -150    -5    -1 12000   400    80]
 [ -150  -150    -1     0     0     0 33000 33000   220]
 [    0     0     0  -150  -150    -1 12000 12000    80]
 [   -5  -150    -1     0     0     0   500 15000   100]
 [    0     0     0    -5  -150    -1  1000 30000   200]]
 
The Transpose of the A matrix (At) is: 
[[   -5     0  -150     0  -150     0    -5     0]
 [   -5     0    -5     0  -150     0  -150     0]
 [   -1     0    -1     0    -1     0    -1     0]
 [    0    -5     0  -150     0  -150     0    -5]
 [    0    -5     0    -5     0  -150     0  -150]
 [    0    -1     0    -1     0    -1     0    -1]
 [  500   500 30000 12000 33000 12000   500  1000]
 [  500   500  1000   400 33000 12000 15000 30000]
 [  100   100   200    80   220    80   100   200]]


In [4]:
# Product of A and A transpose (At)
A1 = np.dot(A,At)
print 'The value of A*At is: ' 
print A1

print ' '
# Eigen values and vectors of A*At
ei1, eiv1 = la.eig(A1) 
eiv1 = np.array(eiv1)

#Sorting the Eigen values in descending order and getting the indices
id1 = np.argsort(-ei1, axis = -1)

print 'Eigen Values for AAt are:' 
print ei1 
print '                                                                                         '
print 'Sorted Eigen values for AAt are: '
print ei1[id1]
print ' '
print 'Eigen Vectors for AAt are:' 
print eiv1
print 'Sorted Eigen vectors for AAt are: '
print eiv1[:,id1]
print ' '
print '*****************************************************************************************'
# Product of At and A 
A2 = np.dot(At,A)
print 'The value of At*A is: ' 
print A2
print ' '
# Eigen values and eigen vectors of At*A
ei2, eiv2 = la.eig(A2)
eiv2 = np.array(eiv2)

#Sorting the Eigen values in descending order and getting the indices
id2 = np.argsort(-ei2, axis = -1)

print 'Eigen Values for AtA are:' 
print ei2
print '                                                                                         '
print 'Sorted Eigen values for AtA are: '
print ei2[id2]
print ' '
print 'Eigen Vectors for AtA are:' 
print eiv2
print 'Sorted Eigen vectors for AtA are: '
print eiv2[:,id2]
print ' '

The value of A*At is: 
[[    510051     510000   15520776    6208000   33023501   12008000
     7760776   15520000]
 [    510000     510051   15520000    6208776   33022000   12009501
     7760000   15520776]
 [  15520776   15520000  901062526  360416000 1023067251  372016000
    30021501   60040000]
 [   6208000    6208776  360416000  144188926  409217600  148829651
    12008000   24017501]
 [  33023501   33022000 1023067251  409217600 2178093401  792017600
   511545251 1023044000]
 [  12008000   12009501  372016000  148829651  792017600  288051401
   186008000  372039251]
 [   7760776    7760000   30021501   12008000  511545251  186008000
   225282526  450520000]
 [  15520000   15520776   60040000   24017501 1023044000  372039251
   450520000  901062526]]
 
Eigen Values for AAt are:
[  3.62583363e+09   1.01280011e+09   6.80651927e+04   3.46776193e+04
   2.12012335e+04   3.70648899e+03   6.56490959e-01   1.52001454e+01]
                                                                 

In [5]:
# Transpose of Eigen vectors of A*At and At*A as U and V are matrix of column vectors
U = eiv1[:,id1]
V = eiv2[:,id2]
print 'U is: ' 
print eiv1
print ' '
print 'V is: '
print eiv2


U is: 
[[ 0.01175199  0.00034421 -0.05155322 -0.46612859 -0.2603459  -0.06784286
  -0.84108777  0.01081229]
 [ 0.01175178  0.00034364 -0.08721037 -0.45935196 -0.24909895 -0.08855919
   0.35416947  0.76545599]
 [ 0.3587357   0.65494291  0.01345387 -0.46508449  0.17010164  0.29361752
   0.18228987 -0.27838548]
 [ 0.14349422  0.26197639 -0.44538312  0.13606022 -0.50079553 -0.58748815
   0.15289724 -0.27309929]
 [ 0.77496268  0.02271174  0.40851616  0.28493736  0.03196427 -0.23521144
  -0.15965835  0.26268869]
 [ 0.28180663  0.00824746 -0.69216714  0.31591557  0.01141497  0.50190881
  -0.16956061  0.24662816]
 [ 0.18464341 -0.31680626  0.24846634 -0.0346545  -0.69826827  0.46726159
   0.18163034 -0.25239374]
 [ 0.36927845 -0.63361492 -0.28891722 -0.39333329  0.31891754 -0.17501653
   0.15263361 -0.261429  ]]
 
V is: 
[[ 0.00284044  0.0031443  -0.24638474 -0.15855493 -0.17524511  0.17670564
   0.91373863 -0.12026107  0.05310564]
 [ 0.00242122 -0.00128322 -0.37700073  0.17660022  0.68950815 

In [6]:
# Value of sigma obtained by taking diagonal matrix of square roots of eigen values of A*At
sigma = np.array(np.diag(np.sqrt(ei1[id1])))
zero_column = np.array([0,0,0,0,0,0,0,0])
sigma = np.column_stack((sigma, zero_column))
print 'Sigma is: ' 
print sigma
print ' '

Sigma is: 
[[ 60214.89538892      0.              0.              0.              0.
       0.              0.              0.              0.        ]
 [     0.          31824.52065484      0.              0.              0.
       0.              0.              0.              0.        ]
 [     0.              0.            260.89306752      0.              0.
       0.              0.              0.              0.        ]
 [     0.              0.              0.            186.21927755      0.
       0.              0.              0.              0.        ]
 [     0.              0.              0.              0.            145.60643368
       0.              0.              0.              0.        ]
 [     0.              0.              0.              0.              0.
      60.88094109      0.              0.              0.        ]
 [     0.              0.              0.              0.              0.
       0.              3.89873639      0.              0.    

In [7]:
# U, Sigma and V computed from the numpy SVD function to compare with obtained values
u, s, vh = np.linalg.svd(A)
print 'U from SVD Function is: ' 
print u
print ' '
print 'Sigma from SVD function is: ' 
print s
print ' '
print 'V from SVD Function is: ' 
print (np.transpose(np.array(vh)))

U from SVD Function is: 
[[ 0.01175199  0.00034421  0.05155322 -0.46612859 -0.2603459  -0.06784286
   0.01081229  0.84108777]
 [ 0.01175178  0.00034364  0.08721037 -0.45935196 -0.24909895 -0.08855919
   0.76545599 -0.35416947]
 [ 0.3587357   0.65494291 -0.01345387 -0.46508449  0.17010164  0.29361752
  -0.27838548 -0.18228987]
 [ 0.14349422  0.26197639  0.44538312  0.13606022 -0.50079553 -0.58748815
  -0.27309929 -0.15289724]
 [ 0.77496268  0.02271174 -0.40851616  0.28493736  0.03196427 -0.23521144
   0.26268869  0.15965835]
 [ 0.28180663  0.00824746  0.69216714  0.31591557  0.01141497  0.50190881
   0.24662816  0.16956062]
 [ 0.18464341 -0.31680626 -0.24846634 -0.0346545  -0.69826827  0.46726159
  -0.25239374 -0.18163034]
 [ 0.36927845 -0.63361492  0.28891722 -0.39333329  0.31891754 -0.17501653
  -0.261429   -0.15263361]]
 
Sigma from SVD function is: 
[ 60214.89538892  31824.52065484    260.89306752    186.21927755
    145.60643368     60.88094109      3.89873638      0.81024131]
 
V 

In [8]:
#The value of x for which Ax=0 is the Eigen vector corresponding to the eigen value = 0 of At*A
# X is the last column of the sorted Eigen vector matrix for At*A, since it corresponds to eigen value = 0
x = np.array(eiv2[:,id2])[:,8]
print 'The Value of x obtained is: '
print x
print ' '
# To confirm the solution of Ax = 0, multiplying A and X to check if 0
print 'Value of A*X is :'
print np.matmul(A, x)

The Value of x obtained is: 
[ 0.05310564 -0.00491719  0.61464855  0.01770188 -0.00393375  0.78675015
  0.00023603 -0.00004917  0.00762164]
 
Value of A*X is :
[ 0.  0. -0. -0.  0.  0.  0. -0.]


In [9]:
# H is the Homography matrix obtained from x
h1 = x[0:3]
h2 = x[3:6]
h3 = x[6:9]

H = np.transpose(np.column_stack((np.column_stack((h1, h2)), h3)))
print 'The homography matrix H is: '
print ' '
print H

The homography matrix H is: 
 
[[ 0.05310564 -0.00491719  0.61464855]
 [ 0.01770188 -0.00393375  0.78675015]
 [ 0.00023603 -0.00004917  0.00762164]]
